### PR TITLE
Remove yarn check and add ruby 2.6

### PR DESCRIPTION
**Pull request by cschiewek**
### Purpose
`yarn check` is slow.  It actually takes ~5 times longer to run then a no-op `yarn install` on SBN.

```
$ time yarn check
real    0m27.262s
user    0m16.740s
sys     0m18.850s
```
```
$ time yarn install
real    0m6.021s
user    0m3.120s
sys     0m2.260s
```

The reasoning behind the yarn check before yarn install was to speed things up, but its' actually having the opposite effect, so let's just remove it.

### Changes
- Remove `yarn check` conditional
- Move the message inside the directory check, as we're not actually checking anything if the dir is empty
- Add ruby 2.6 series to the build process

### Tests
- I smoke tested the new ruby 2.6 image locally

### Launch Plan
Merge on approval

### CODE REVIEW

**Comment by cschiewek** [comment]
That's not the case for me at all.  `yarn check` is always slow for me... 
```
🙈 ➜  sbn git:(master) ✗ dco down
Removing network sbn_default
WARNING: Network sbn_default not found.
Network !docker-ssh-exec is external, skipping
🙈 ➜  sbn git:(master) ✗ docker volume rm sbn_node_modules
sbn_node_modules
🙈 ➜  sbn git:(master) ✗ dcra bash
Creating network "sbn_default" with the default driver
Creating volume "sbn_node_modules" with default driver
Creating sbn_redis_1     ... done
Creating sbn_mysql_1     ... done
Creating sbn_elastic_1   ... done
Creating sbn_dns_1       ... done
Creating sbn_memcached_1 ... done
Creating sbn_stats_1     ... done
Creating sbn_sync_1      ... done
Creating sbn_webpack_1   ... done
Broadcasting UDP key request...
Got key from server.
Writing key to /root/.ssh/id_rsa
Running command: /opt/entrypoint/dispatcher.sh base_image_check bundle yarn use_dns_server cleanup_pids service_health_checks/mysql service_health_checks/elasticsearch service_health_checks/redis -- bash
The current base image (3.1.9) is up-to-date! 👍
Checking bundle
The Gemfile's dependencies are satisfied
Verifying node modules are up-to-date with yarn
error "arr-diff" is wrong version: expected "4.0.0", got "2.0.0"
...
error Found 473 errors.

real    0m38.796s
user    0m28.270s
sys     0m23.920s
warning "@rails/webpacker > postcss-cssnext@3.0.2" has unmet peer dependency "caniuse-lite@^1.0.30000697".

real    0m34.519s
user    0m21.350s
sys     0m17.930s
root@ced5410dc252:/sbn# exit
exit
Command completed successfully.
Starting sbn_dns_1       ... done
🙈 ➜  sbn git:(master) ✗ dcra bash
Starting sbn_sync_1      ... done
Starting sbn_webpack_1   ... done
Starting sbn_redis_1     ... done
Starting sbn_stats_1     ... done
Starting sbn_elastic_1   ... done
Starting sbn_mysql_1     ... done
Broadcasting UDP key request...
Got key from server.
Writing key to /root/.ssh/id_rsa
Running command: /opt/entrypoint/dispatcher.sh base_image_check bundle yarn use_dns_server cleanup_pids service_health_checks/mysql service_health_checks/elasticsearch service_health_checks/redis -- bash
The current base image (3.1.9) is up-to-date! 👍
Checking bundle
The Gemfile's dependencies are satisfied
Verifying node modules are up-to-date with yarn
warning "webpack-dev-server#array-includes#es-abstract@^1.7.0" could be deduped from "1.11.0" to "es-abstract@1.11.0"

real    0m42.808s
user    0m28.370s
sys     0m22.360s

real    0m9.190s
user    0m4.470s
sys     0m2.890s
root@5bb1ac66b97f:/sbn# exit
exit
Command completed successfully.
Deleting key file /root/.ssh/id_rsa...
🙈 ➜  sbn git:(master) ✗ dcra bash
Starting sbn_memcached_1 ... done
Starting sbn_sync_1      ... done
Starting sbn_dns_1       ... done
Starting sbn_stats_1     ... done
Starting sbn_elastic_1   ... done
Starting sbn_redis_1     ... done
Broadcasting UDP key request...
Got key from server.
Writing key to /root/.ssh/id_rsa
Running command: /opt/entrypoint/dispatcher.sh base_image_check bundle yarn use_dns_server cleanup_pids service_health_checks/mysql service_health_checks/elasticsearch service_health_checks/redis -- bash
The current base image (3.1.9) is up-to-date! 👍
Checking bundle
The Gemfile's dependencies are satisfied
Verifying node modules are up-to-date with yarn
warning "webpack-dev-server#array-includes#es-abstract@^1.7.0" could be deduped from "1.11.0" to "es-abstract@1.11.0"

real    0m42.727s
user    0m29.350s
sys     0m22.480s

real    0m10.997s
user    0m5.760s
sys     0m3.210s
root@7aa06b0161ca:/sbn#```

Which was run via this temporary replacement yarn.sh 
```
#!/bin/bash
if [ "$(ls -A ./node_modules 2> /dev/null)" ]; then
  echo "Verifying node modules are up-to-date with yarn"
  time yarn check --silent
  time yarn install --silent --check-files
fi
```

**Comment by cschiewek** [comment]
It looks like it's the context of running in an entrypoint that slows it down.  If I run in the bash shell it's faster
```
root@9006cfe641e0:/sbn# time yarn check --silent
warning "webpack-dev-server#array-includes#es-abstract@^1.7.0" could be deduped from "1.11.0" to "es-abstract@1.11.0"

real    0m10.434s
user    0m6.250s
sys     0m3.190s
```
but basically the same speed as the `yarn install` in the entrypoint

**Comment by thenonsequitur** [comment]
I'm not at a computer atm so can't copy/paste data, but I definitely remember seeing the same result as Curtis with native docker on Linux, more pronounced even. Yarn check was like 10x slower than yarn install.

**Comment by jamiemccarthy** [comment]
`yarn check` run as an entrypoint is twice as fast for me as `yarn install`.

Neither of them is _fast_. They both take too long. But 30s is better than 60s.

[Here's a PR](https://github.com/voxmedia/sbn/pull/8474) with the exact changes I made, and the commit messages include the timing information, if you want to reproduce what I did.

This is with nothing else running on my local docker, zoom not running, no expensive programs running.

**Comment by cschiewek** [comment]
So, I've managed to get @jamiemccarthy's branch working.  I've pushed my changes here:
https://github.com/voxmedia/sbn/tree/yarn-install-and-check-ccs

When running both check and install as part of the entrypoint, check is _always_ slow for me, and install is only slow when it's first run, otherwise it's sun 10seconds...

First run times
```
# check
real    1m21.006s
user    0m45.110s
sys     0m37.460s
# install
real    1m4.721s
user    0m19.580s
sys 0m15.750s
```
Subsequent run times
```
# check
real    1m4.421s
user    0m41.870s
sys     0m29.070s
# install
real    0m7.486s
user    0m3.420s
sys 0m2.820s
```

My full shell output is here: https://gist.github.com/cschiewek/003869879e8f981a6c12c21782014115

**Comment by thenonsequitur** [comment]
As mentioned in my previous comment, my numbers follow the same pattern as Curtis's.

First run:

```
# check
real    0m15.890s
user    0m16.436s
sys     0m5.366s
```

```
# install
real    0m20.337s
user    0m12.007s
sys     0m4.703s
````

Second run:

```
# check
real    0m17.979s
user    0m16.715s
sys     0m5.773s
```

```
# install
real    0m2.139s
user    0m2.042s
sys     0m0.605s
```

**Comment by jamiemccarthy** [comment]
Just in case anyone is reading this in the future ... I  did comment twice above that yarn check is faster than a no-op yarn  install, but after this change was pushed and incorporated into sbn, the install is much  faster.  I don't have an explanation for why it was  slower in my testing and faster  once  using the actual base  image.

**Comment by okor** [comment]
@jamiemccarthy I'm happy to hear that!!

**Pull request merged**
